package com.flying.orm.rdb.jdbc;

import com.flying.orm.core.sql.render.SqlBindMarkerStyle;
import com.flying.orm.core.sql.render.SqlRequest;
import com.flying.orm.rdb.batch.BatchGeneratedKeys;
import com.flying.orm.rdb.batch.BatchRowCountPolicy;
import com.flying.orm.rdb.batch.BatchWriteOptions;
import com.flying.orm.rdb.batch.BatchWriteRequest;
import com.flying.orm.rdb.batch.BatchWriteRequests;
import com.flying.orm.rdb.execution.ProtectedBatchRows;
import com.flying.orm.rdb.execution.ProtectedWriteWork;
import org.junit.jupiter.api.Test;
import reactor.core.publisher.Flux;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Proxy;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

class JdbcGeneratedFallbackBudgetTest {

    @Test
    void generatedFallbackSplitsTokenBindingsAtTheConfiguredByteBudget() throws Exception {
        try (Connection database = database()) {
            List<Integer> insertBatchSizes = new ArrayList<>();

            execute(recordBatches(database, insertBatchSizes), 200L);

            assertEquals(List.of(1, 1, 1), insertBatchSizes);
            try (var statement = database.createStatement();
                 var rows = statement.executeQuery("select count(*) from tokens")) {
                rows.next();
                assertEquals(3, rows.getInt(1));
            }
        }
    }

    @Test
    void generatedFallbackRejectsASingleTokenBindingAboveTheConfiguredByteBudget() throws Exception {
        try (Connection database = database()) {
            List<Integer> insertBatchSizes = new ArrayList<>();

            assertThrows(IllegalArgumentException.class,
                    () -> execute(recordBatches(database, insertBatchSizes), 150L));

            assertEquals(List.of(), insertBatchSizes);
        }
    }

    private static void execute(Connection connection, long maxBufferedBytes) throws SQLException {
        String sql = "insert into samples(value_col) values (?)";
        ProtectedWriteWork work = new ProtectedWriteWork(ProtectedWriteWork.Kind.UPSERT,
                new SqlRequest(sql, List.of("value")), null, List.of("id"), Map.of("id", 7L), "id=?",
                "delete from tokens where id=? and field_tag=?",
                "insert into tokens(id,field_tag,token) values (?,?,?)",
                List.of(new ProtectedWriteWork.FieldTokens("value_col",
                        List.of(new byte[32], new byte[32], new byte[32]))));
        BatchWriteRequest base = BatchWriteRequests.request(sql, 1, List.of(String.class),
                SqlBindMarkerStyle.CANONICAL, Flux.empty(),
                BatchWriteOptions.of(1).withMemoryLimits(0, maxBufferedBytes));
        BatchWriteRequest request = new BatchWriteRequest(base.statement(), base.parameterTypes(),
                base.rows(), base.options(), BatchRowCountPolicy.ANY,
                BatchGeneratedKeys.required("id", (offset, key) -> {}));
        ProtectedBatchRows.RowView row = ProtectedBatchRows.decode(
                ProtectedBatchRows.extend(new Object[]{"value"}, work), 1);

        new JdbcBatchChunkExecutor().execute(connection, request, 0L, List.of(row),
                new JdbcBatchEvidenceSupport.Counts(0L, 1, BatchRowCountPolicy.ANY));
    }

    private static Connection database() throws SQLException {
        Connection database = DriverManager.getConnection("jdbc:h2:mem:fallback_budget_" + UUID.randomUUID());
        try (var statement = database.createStatement()) {
            statement.execute("create table samples(id bigint generated by default as identity, value_col varchar)");
            statement.execute("create table tokens(id bigint, field_tag varchar, token varbinary)");
        }
        return database;
    }

    private static Connection recordBatches(Connection database, List<Integer> sizes) {
        return (Connection) Proxy.newProxyInstance(Connection.class.getClassLoader(),
                new Class<?>[]{Connection.class}, (self, method, arguments) -> {
                    try {
                        Object result = method.invoke(database, arguments);
                        if (!method.getName().equals("prepareStatement")
                                || !((String) arguments[0]).startsWith("insert into tokens")) {
                            return result;
                        }
                        PreparedStatement statement = (PreparedStatement) result;
                        int[] count = {0};
                        return Proxy.newProxyInstance(PreparedStatement.class.getClassLoader(),
                                new Class<?>[]{PreparedStatement.class}, (proxy, call, values) -> {
                                    if (call.getName().equals("addBatch")) count[0]++;
                                    if (call.getName().equals("executeBatch")) sizes.add(count[0]);
                                    try {
                                        return call.invoke(statement, values);
                                    } catch (InvocationTargetException error) {
                                        throw error.getCause();
                                    }
                                });
                    } catch (InvocationTargetException error) {
                        throw error.getCause();
                    }
                });
    }
}
