package com.flying.orm.rdb.reactive;

import com.flying.orm.core.sql.render.SqlRequest;
import com.flying.orm.rdb.execution.SqlExecutionOptions;
import io.r2dbc.h2.H2ConnectionConfiguration;
import io.r2dbc.h2.H2ConnectionFactory;
import org.junit.jupiter.api.Test;
import reactor.test.StepVerifier;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

/** 只验证生成键和影响行数会从同一次 R2DBC insert 中一起返回。 */
class R2dbcGeneratedKeyWriterTest {

    @Test
    void returnsIdentityKeyWithoutExecutingTheInsertTwice() {
        H2ConnectionFactory connections = new H2ConnectionFactory(
                H2ConnectionConfiguration.builder()
                                         .inMemory("generated_key_writer")
                                         .property("DB_CLOSE_DELAY", "-1")
                                         .build());
        R2dbcSqlExecutor executor = R2dbcSqlExecutor.create(connections);

        StepVerifier.create(executor.rowsUpdated(SqlRequest.nativeSql(
                                    "create table generated_users ("
                                            + "id bigint generated by default as identity primary key, "
                                            + "name varchar(64) not null)",
                                    List.of()))
                            .then(executor.rowsUpdatedReturningKeys(
                                    new SqlRequest("insert into generated_users(name) values (?)", List.of("Alice")),
                                    SqlExecutionOptions.safeDefaults())))
                    .assertNext(result -> {
                        assertEquals(1L, result.affectedRows());
                        assertEquals(1, result.generatedKeys().size());
                        assertEquals(1L, ((Number) result.generatedKeys().getFirst().value(0)).longValue());
                    })
                    .verifyComplete();
    }
}
