package com.flying.orm.rdb.dialect;

import com.flying.orm.core.condition.ConditionGroup;
import com.flying.orm.core.form.DynamicField;
import com.flying.orm.core.form.DynamicForm;
import com.flying.orm.core.page.PageQuery;
import com.flying.orm.core.page.PageSort;
import com.flying.orm.core.sql.render.SqlRenderer;
import com.flying.orm.core.sql.render.SqlRequest;
import com.flying.orm.core.sql.render.SqlTermHandler;
import com.flying.orm.rdb.batch.BatchWriteRequest;
import com.flying.orm.rdb.form.FormDataSqlRenderer;
import com.flying.orm.rdb.schema.FormSchemaSqlRenderer;
import org.junit.jupiter.api.Test;
import reactor.core.publisher.Flux;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * 把 Oracle、SQL Server 第二阶段承诺集中成纯 SQL 契约。这里不连接数据库，失败时能直接看出是版本边界、
 * DDL、分页还是批量 MERGE 的渲染发生了变化。
 */
class OracleSqlServerDialectContractTest {

    @Test
    void exposesConservativeDefaultVersionsAndVersionedTypeCapabilities() {
        RdbDialect oracle19 = RdbDialect.oracle();
        RdbDialect oracle21 = RdbDialect.oracle(OracleVersion.V21C);
        RdbDialect oracle23 = RdbDialect.oracle(OracleVersion.V23AI);
        RdbDialect sqlServer2012 = RdbDialect.sqlServer(SqlServerVersion.V2012);
        RdbDialect sqlServer2016 = RdbDialect.sqlServer(SqlServerVersion.V2016);

        assertEquals("19c", oracle19.version());
        assertEquals("CLOB", oracle19.schema().dataType("JSON"));
        assertEquals("JSON", oracle21.schema().dataType("JSON"));
        assertEquals("NUMBER(1)", oracle21.schema().dataType("BOOLEAN"));
        assertEquals("BOOLEAN", oracle23.schema().dataType("BOOLEAN"));
        assertTrue(oracle19.supports(DialectFeature.IDENTITY_COLUMNS));
        assertTrue(oracle19.supports(DialectFeature.SEQUENCES));

        assertEquals("2012", sqlServer2012.version());
        assertFalse(sqlServer2012.supports(DialectFeature.JSON_FUNCTIONS));
        assertTrue(sqlServer2016.supports(DialectFeature.JSON_FUNCTIONS));
        assertTrue(sqlServer2012.supports(DialectFeature.IDENTITY_COLUMNS));
        assertTrue(sqlServer2012.supports(DialectFeature.MERGE_UPSERT));
    }

    @Test
    void rendersOracleSequenceAndIdentityColumnsBeforeTheTable() {
        DynamicForm form = DynamicForm.builder("users", "Users")
                                      .addField(DynamicField.primaryKey("id", "BIGINT")
                                                            .generatedBySequence("users_seq", 100, 1, 128))
                                      .addField(DynamicField.of("audit_id", "BIGINT")
                                                            .generatedByIdentity(1, 1, 128))
                                      .addField(DynamicField.of("name", "VARCHAR").withLength(64))
                                      .build();

        List<String> sql = FormSchemaSqlRenderer.create(RdbDialect.oracle())
                                                .createTable(form)
                                                .stream()
                                                .map(SqlRequest::sql)
                                                .toList();

        assertEquals(List.of(
                "create sequence \"users_seq\" start with 100 increment by 1 cache 128",
                "create table \"Users\" (\"id\" NUMBER(19) default \"users_seq\".nextval primary key, "
                        + "\"audit_id\" NUMBER(19) generated by default on null as identity "
                        + "(start with 1 increment by 1 cache 128), \"name\" VARCHAR2(64))"), sql);
    }

    @Test
    void rendersSqlServerIdentityAndDatabaseSpecificAlterColumnSyntax() {
        DynamicForm form = DynamicForm.builder("users", "dbo.Users")
                                      .addField(DynamicField.primaryKey("id", "BIGINT")
                                                            .generatedByIdentity())
                                      .addField(DynamicField.of("serial_no", "BIGINT")
                                                            .generatedBySequence("users_serial_seq", 10, 5, 64))
                                      .addField(DynamicField.of("name", "VARCHAR").withLength(64))
                                      .build();

        List<String> createSql = FormSchemaSqlRenderer.create(RdbDialect.sqlServer())
                                                       .createTable(form)
                                                       .stream()
                                                       .map(SqlRequest::sql)
                                                       .toList();
        DynamicForm oracleSource = DynamicForm.builder("users", "Users")
                                              .addField(DynamicField.of("name", "VARCHAR").withLength(64))
                                              .build();
        DynamicForm oracleTarget = DynamicForm.builder("users", "Users")
                                              .addField(DynamicField.of("name", "VARCHAR").withLength(128))
                                              .build();

        assertEquals(List.of(
                             "create sequence [users_serial_seq] as BIGINT start with 10 increment by 5 cache 64",
                             "create table [dbo].[Users] ([id] BIGINT identity(1,1) not null primary key, "
                                      + "[serial_no] BIGINT default next value for [users_serial_seq] null, "
                                      + "[name] NVARCHAR(64) null)"),
                     createSql);
        assertEquals("alter table \"Users\" modify (\"name\" VARCHAR2(128))",
                     FormSchemaSqlRenderer.create(RdbDialect.oracle())
                                          .migrate(oracleSource.diffTo(oracleTarget))
                                          .getFirst()
                                          .sql());
        assertEquals("alter table [Users] alter column [name] NVARCHAR(128) null",
                     FormSchemaSqlRenderer.create(RdbDialect.sqlServer())
                                          .migrate(oracleSource.diffTo(oracleTarget))
                                          .getFirst()
                                          .sql());
    }

    @Test
    void sqlServerPaginationRequiresAnExplicitStableSort() {
        DynamicForm form = form();
        FormDataSqlRenderer renderer = renderer(RdbDialect.sqlServer());

        assertThrows(IllegalArgumentException.class,
                     () -> renderer.select(form, ConditionGroup.and().build(), PageQuery.of(1, 20)));

        SqlRequest request = renderer.select(form,
                                             ConditionGroup.and().build(),
                                             PageQuery.of(2, 20, PageSort.asc("id")));
        assertEquals("select [id], [name] from [Users] order by [id] asc offset ? rows fetch next ? rows only",
                     request.sql());
        assertEquals(List.of(20L, 20), request.parameters());
    }

    @Test
    void reusesOneOracleAndSqlServerMergeForEveryBatchParameterGroup() {
        List<Map<String, Object>> rows = List.of(row(1L, "A"), row(2L, "B"));
        BatchWriteRequest oracle = renderer(RdbDialect.oracle()).upsertBatch(form(), rows);
        BatchWriteRequest sqlServer = renderer(RdbDialect.sqlServer()).upsertBatch(form(), rows);

        assertEquals("merge into \"Users\" target using (select ? as \"id\", ? as \"name\" from dual) source "
                             + "on (target.\"id\" = source.\"id\") when matched then update set target.\"name\" = source.\"name\" "
                             + "when not matched then insert (\"id\", \"name\") values (source.\"id\", source.\"name\")",
                     oracle.sql());
        assertEquals("merge into [Users] with (holdlock) as target using (values (?, ?)) as source ([id], [name]) "
                             + "on target.[id] = source.[id] when matched then update set target.[name] = source.[name] "
                             + "when not matched then insert ([id], [name]) values (source.[id], source.[name]);",
                     sqlServer.sql());
        assertEquals(List.of(List.of(1L, "A"), List.of(2L, "B")), parameterRows(oracle));
        assertEquals(parameterRows(oracle), parameterRows(sqlServer));
    }

    @Test
    void rejectsExplicitSqlServerIdentityValuesBeforeCallingTheDriver() {
        DynamicForm identityForm = DynamicForm.builder("users", "Users")
                                              .addField(DynamicField.primaryKey("id", "BIGINT")
                                                                    .generatedByIdentity())
                                              .addField(DynamicField.of("name", "VARCHAR"))
                                              .build();

        assertThrows(IllegalArgumentException.class,
                     () -> renderer(RdbDialect.sqlServer()).insert(identityForm, row(1L, "A")));
        assertThrows(IllegalArgumentException.class,
                     () -> renderer(RdbDialect.sqlServer()).insertBatch(identityForm,
                                                                         List.of(row(1L, "A"), row(2L, "B"))));
        assertEquals(List.of(1L, "A"),
                     renderer(RdbDialect.oracle()).insert(identityForm, row(1L, "A")).parameters());
    }

    private static FormDataSqlRenderer renderer(RdbDialect dialect) {
        return FormDataSqlRenderer.create(SqlRenderer.builder()
                                                     .addTerm(SqlTermHandler.equalsTo())
                                                     .build(),
                                          dialect);
    }

    private static DynamicForm form() {
        return DynamicForm.builder("users", "Users")
                          .addField(DynamicField.primaryKey("id", "BIGINT"))
                          .addField(DynamicField.of("name", "VARCHAR"))
                          .build();
    }

    private static Map<String, Object> row(long id, String name) {
        Map<String, Object> row = new LinkedHashMap<>();
        row.put("id", id);
        row.put("name", name);
        return row;
    }

    private static List<List<Object>> parameterRows(BatchWriteRequest request) {
        return Flux.from(request.rows()).map(Arrays::asList).collectList().block();
    }
}
