package com.flying.orm.rdb.schema;

import com.flying.orm.core.metadata.ColumnDefinition;
import com.flying.orm.core.metadata.RelationIdentity;
import com.flying.orm.core.metadata.RelationalTableDefinition;
import com.flying.orm.core.metadata.ValueGeneration;
import com.flying.orm.core.sql.render.SqlRequest;
import com.flying.orm.rdb.dialect.RdbDialect;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class RelationalIdentityColumnCountTest {

    @Test
    void supportedDialectsKeepEachIdentityDefinition() {
        for (RdbDialect dialect : List.of(RdbDialect.h2(), RdbDialect.postgresql())) {
            List<SqlRequest> requests = assertDoesNotThrow(() -> render(dialect), dialect.name());
            assertEquals(1, requests.size());
            String sql = requests.getFirst().sql();
            assertTrue(sql.contains("generated by default as identity (start with 1 increment by 1)"));
            assertTrue(sql.contains("generated by default as identity (start with 10 increment by 2)"));
        }
    }

    @Test
    void h2GeneratesBothColumnsIndependently() throws Exception {
        try (Connection connection = DriverManager.getConnection("jdbc:h2:mem:" + UUID.randomUUID());
             Statement statement = connection.createStatement()) {
            for (SqlRequest request : render(RdbDialect.h2())) {
                statement.execute(request.sql());
            }
            statement.executeUpdate("insert into identity_columns default values");
            statement.executeUpdate("insert into identity_columns default values");
            try (ResultSet rows = statement.executeQuery(
                    "select id, number from identity_columns order by id")) {
                assertTrue(rows.next());
                assertEquals(1L, rows.getLong(1));
                assertEquals(10L, rows.getLong(2));
                assertTrue(rows.next());
                assertEquals(2L, rows.getLong(1));
                assertEquals(12L, rows.getLong(2));
            }
        }
    }

    @Test
    void dialectsWithOneIdentityColumnStillRejectMultipleDefinitions() {
        for (RdbDialect dialect : List.of(RdbDialect.mysql(), RdbDialect.oracle(), RdbDialect.sqlServer())) {
            assertThrows(UnsupportedOperationException.class, () -> render(dialect), dialect.name());
        }
    }

    private static List<SqlRequest> render(RdbDialect dialect) {
        RelationalTableDefinition table = RelationalTableDefinition.builder(RelationIdentity.table("identity_columns"))
                .addColumn(ColumnDefinition.builder("id", "BIGINT").nullable(false)
                        .generation(ValueGeneration.identity(1, 1, 0)).build())
                .addColumn(ColumnDefinition.builder("number", "BIGINT").nullable(false)
                        .generation(ValueGeneration.identity(10, 2, 0)).build())
                .build();
        return RelationalSchemaSqlRenderer.create(dialect.schema()).render(SchemaOperation.of(
                SchemaOperation.Kind.CREATE_TABLE, table.identity(), table.identity().table(),
                null, table, SchemaOperation.Compatibility.SAFE_INCREMENTAL));
    }
}
