package com.flying.orm.rdb.metadata;

import com.flying.orm.core.form.DynamicField;
import com.flying.orm.core.form.DynamicForm;
import com.flying.orm.core.metadata.TableMetadata;
import com.flying.orm.core.metadata.ValueGeneration;
import com.flying.orm.rdb.dialect.RdbDialect;
import com.flying.orm.rdb.schema.FormSchemaSqlRenderer;
import com.flying.orm.rdb.schema.SchemaMigrationOptions;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.Statement;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class JdbcFormMetadataSequenceTest {

    @Test
    void preservesSequenceOwnershipThroughTheRealMetadataReader() throws Exception {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:metadata_sequence;DB_CLOSE_DELAY=-1");
        dataSource.setUser("sa");
        dataSource.setPassword("");
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute("create sequence \"shared_seq\" start with 1 increment by 1 cache 100");
            statement.execute("create table events (id bigint, old_value bigint default next value for \"shared_seq\")");
        }

        TableMetadata current = JdbcFormMetadataReaders.create(dataSource, RdbDialect.h2())
                                                        .readTable("events");
        assertEquals(ValueGeneration.Strategy.SEQUENCE,
                     current.column("old_value").generation().strategy());
        assertEquals("shared_seq", current.column("old_value").generation().sequenceName());

        DynamicForm target = DynamicForm.builder("events", "events")
                                        .addField(DynamicField.of("id", "BIGINT"))
                                        .addField(DynamicField.of("new_value", "BIGINT")
                                                              .generatedBySequence("shared_seq"))
                                        .build();
        long sequenceCreates = FormSchemaSqlRenderer.create(RdbDialect.h2())
                                                    .migrateSafelyPlan(
                                                            current,
                                                            target,
                                                            List.of(),
                                                            SchemaMigrationOptions.safe().allowDropColumn())
                                                    .sqlTexts()
                                                    .stream()
                                                    .filter(sql -> sql.startsWith("create sequence "))
                                                    .count();

        assertEquals(0, sequenceCreates);
    }

    @Test
    void readsIdentityThroughTheRealH2MetadataReader() throws Exception {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:metadata_identity;DB_CLOSE_DELAY=-1");
        dataSource.setUser("sa");
        dataSource.setPassword("");
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute("create table events (id bigint generated by default as identity primary key)");
        }

        TableMetadata current = JdbcFormMetadataReaders.create(dataSource, RdbDialect.h2())
                                                        .readTable("events");

        assertEquals(ValueGeneration.Strategy.IDENTITY,
                     current.column("id").generation().strategy());
    }

    @Test
    void recognizesOnlyTheNamedSequenceDefaultsRenderedBySupportedDialects() {
        assertEquals("public.CaseSeq", sequenceName("nextval('public.\"CaseSeq\"'::regclass)"));
        assertEquals("dbo.shared_seq", sequenceName("(NEXT VALUE FOR [dbo].[shared_seq])"));
        assertEquals("CaseSeq", sequenceName("\"CaseSeq\".NEXTVAL"));
        assertEquals("CaseSeq",
                     sequenceName("nextval('public.\"CaseSeq\"'::regclass)", "public"));
        assertEquals("archive.CaseSeq",
                     sequenceName("nextval('archive.\"CaseSeq\"'::regclass)", "public"));
        assertEquals("tenant.CaseSeq",
                     sequenceName("nextval('tenant.\"CaseSeq\"'::regclass)", "public"));
        assertEquals(ValueGeneration.Strategy.NONE,
                     generation("nextval('shared_seq'::regclass) + 1").strategy());
    }

    @Test
    void safeMigrationDoesNotInventOptionsForAnExistingPhysicalSequence() throws Exception {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:metadata_custom_sequence;DB_CLOSE_DELAY=-1");
        dataSource.setUser("sa");
        dataSource.setPassword("");
        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute("create sequence \"custom_seq\" start with 10 increment by 2 cache 50");
            statement.execute("create table events (old_value bigint default next value for \"custom_seq\")");
        }
        TableMetadata current = JdbcFormMetadataReaders.create(dataSource, RdbDialect.h2())
                                                        .readTable("events");
        DynamicForm target = DynamicForm.builder("events", "events")
                                        .addField(DynamicField.of("old_value", "BIGINT")
                                                              .withGeneration(ValueGeneration.sequence(
                                                                      "custom_seq", 10, 2, 50)))
                                        .addField(DynamicField.of("description", "VARCHAR").withLength(64))
                                        .build();

        List<String> sql = FormSchemaSqlRenderer.create(RdbDialect.h2())
                                                .migrateSafelyPlan(current, target, List.of())
                                                .sqlTexts();

        assertTrue(sql.stream().noneMatch(statement -> statement.startsWith("create sequence ")));
    }

    @Test
    void allMetadataQueriesProjectStableGeneratedValueAliases() {
        List<InformationSchemaFormMetadataReader.Queries> readers = List.of(
                H2ReactiveFormMetadataReader.queries(),
                MySqlReactiveFormMetadataReader.queries(),
                PostgreSqlReactiveFormMetadataReader.queries(),
                OracleReactiveFormMetadataReader.queries(),
                SqlServerReactiveFormMetadataReader.queries());

        assertTrue(readers.stream().allMatch(queries -> {
            String sql = queries.columnQuery().create(null, "events").sql();
            return sql.contains("GENERATION_EXPRESSION")
                    && sql.contains("RESOLUTION_SCHEMA")
                    && sql.contains("IS_IDENTITY");
        }));
    }

    @Test
    void oracleMetadataUsesTheDefaultExpressionColumnAvailableInSupportedVersions() {
        String sql = OracleReactiveFormMetadataReader.queries()
                                                     .columnQuery()
                                                     .create(null, "events")
                                                     .sql();

        assertTrue(sql.contains("c.DATA_DEFAULT as GENERATION_EXPRESSION"));
        assertFalse(sql.contains("DATA_DEFAULT_VC"));
    }

    private static String sequenceName(String expression) {
        return generation(expression).sequenceName();
    }

    private static String sequenceName(String expression, String resolutionSchema) {
        return generation(expression, resolutionSchema).sequenceName();
    }

    private static ValueGeneration generation(String expression) {
        return generation(expression, null);
    }

    private static ValueGeneration generation(String expression, String resolutionSchema) {
        Map<String, Object> row = new java.util.HashMap<>();
        row.put("COLUMN_NAME", "generated_value");
        row.put("DATA_TYPE", "BIGINT");
        row.put("NULLABLE", true);
        row.put("GENERATION_EXPRESSION", expression);
        if (resolutionSchema != null) {
            row.put("RESOLUTION_SCHEMA", resolutionSchema);
        }
        return FormMetadataRowConverter.toDynamicForm(
                                               "events",
                                               "events",
                                               List.of(row),
                                               value -> value)
                                       .field("generated_value")
                                       .generation();
    }
}
