package com.flying.orm.rdb.metadata;

import com.flying.orm.core.annotation.IdType;
import com.flying.orm.core.annotation.TableCheck;
import com.flying.orm.core.annotation.TableColumn;
import com.flying.orm.core.annotation.TableComment;
import com.flying.orm.core.annotation.TableForeignKey;
import com.flying.orm.core.annotation.TableId;
import com.flying.orm.core.annotation.TableIndex;
import com.flying.orm.core.annotation.TableIndexColumn;
import com.flying.orm.core.annotation.TableName;
import com.flying.orm.core.annotation.TablePrimaryKey;
import com.flying.orm.core.annotation.TableUnique;
import com.flying.orm.core.metadata.ReferentialAction;
import com.flying.orm.core.metadata.RelationalTableDefinition;
import com.flying.orm.rdb.cache.CacheRegionPolicy;
import com.flying.orm.rdb.dialect.DatabaseDescriptor;
import com.flying.orm.rdb.dialect.RdbDialect;
import com.flying.orm.rdb.jdbc.JdbcSqlExecutor;
import com.flying.orm.rdb.mapping.EntityModelRegistry;
import com.flying.orm.rdb.mapping.EntitySchemaDescriptor;
import com.flying.orm.rdb.schema.EntityRelationalSchemaSyncReport;
import com.flying.orm.rdb.schema.EntitySchemaSyncMode;
import com.flying.orm.rdb.schema.EntitySchemaSynchronizer;
import com.flying.orm.rdb.schema.JdbcSchemaClient;
import com.flying.orm.rdb.schema.RelationalSchemaSqlRenderer;
import com.flying.orm.rdb.schema.ReviewedSchemaPlan;
import com.flying.orm.rdb.schema.SchemaCompatibilityMode;
import com.flying.orm.rdb.schema.SchemaMigrationApproval;
import com.flying.orm.rdb.schema.SchemaSnapshot;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;

import javax.sql.DataSource;
import java.io.IOException;
import java.io.PrintWriter;
import java.math.BigDecimal;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.UUID;
import java.util.logging.Logger;

import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * 本机 PostgreSQL/MySQL 的显式认证入口。
 *
 * <p>测试只在提供 {@code flying.orm.it.config} 时运行。配置文件不进入 Git，内容为两个数据库的
 * URL、测试账号和口令。每次运行创建随机隔离 namespace，成功或失败都会只清理本次创建的对象。</p>
 */
@EnabledIfSystemProperty(named = "flying.orm.it.config", matches = ".+")
class LocalDatabaseSchemaRoundTripIT {

    @Test
    void postgresqlEntityAnnotationsRoundTripExactly() throws Exception {
        certify(Database.POSTGRESQL, RdbDialect.postgresql());
    }

    @Test
    void postgresqlRejectsDatabaseFactsOutsideTheClosedEntityModel() throws Exception {
        Properties configuration = configuration();
        String url = required(configuration, "postgresql.url");
        String user = required(configuration, "postgresql.user");
        String password = required(configuration, "postgresql.password");
        String namespace = "flying_orm_32_guard_" + UUID.randomUUID().toString().replace("-", "");
        boolean created = false;
        try (Connection administration = DriverManager.getConnection(url, user, password)) {
            execute(administration, Database.POSTGRESQL.createNamespace(namespace));
            created = true;
            DataSource scoped = new ScopedDataSource(
                    url, user, password, Database.POSTGRESQL.enterNamespace(namespace));
            try (Connection connection = scoped.getConnection()) {
                execute(connection, "create table fo32_rt_bad_default (value text default ('x'::text || 'y'::text))");
                execute(connection, "create table fo32_rt_bad_sequence "
                        + "(id bigint generated by default as identity (maxvalue 10))");
                execute(connection, "create table fo32_rt_bad_unique "
                        + "(code varchar(32), payload varchar(32), "
                        + "constraint uk_fo32_rt_bad_unique unique (code) include (payload))");
            }
            JdbcSqlExecutor executor = JdbcSqlExecutor.create(scoped, RdbDialect.postgresql());
            JdbcFormMetadataReader reader = JdbcFormMetadataReaders.create(executor, RdbDialect.postgresql());

            assertThrows(IllegalStateException.class, () -> reader.readSnapshot("fo32_rt_bad_default"));
            assertThrows(IllegalStateException.class, () -> reader.readSnapshot("fo32_rt_bad_sequence"));
            assertThrows(IllegalStateException.class, () -> reader.readSnapshot("fo32_rt_bad_unique"));
        } finally {
            if (created) {
                try (Connection administration = DriverManager.getConnection(url, user, password)) {
                    execute(administration, Database.POSTGRESQL.dropNamespace(namespace));
                }
            }
        }
    }

    @Test
    void mysqlEntityAnnotationsRoundTripExactly() throws Exception {
        certify(Database.MYSQL, RdbDialect.mysql());
    }

    @Test
    void h2EntityAnnotationsRoundTripExactly() throws Exception {
        String databaseName = "fo32_" + UUID.randomUUID().toString().replace("-", "");
        certify(Database.H2, RdbDialect.h2(),
                "jdbc:h2:mem:" + databaseName + ";DB_CLOSE_DELAY=-1", "sa", "");
    }

    @Test
    void oracleEntityAnnotationsRoundTripExactly() throws Exception {
        Properties configuration = configuration();
        String url = required(configuration, "oracle.url");
        String administrator = required(configuration, "oracle.user");
        String administratorPassword = required(configuration, "oracle.password");
        String schemaPassword = required(configuration, "oracle.schemaPassword");
        String schema = "FO32_" + UUID.randomUUID().toString().replace("-", "").substring(0, 20);
        try (Connection connection = DriverManager.getConnection(url, administrator, administratorPassword)) {
            execute(connection, "create user " + schema + " identified by \"" + schemaPassword + "\"");
            execute(connection, "grant create session, create table, create sequence to " + schema);
            execute(connection, "alter user " + schema + " quota unlimited on users");
        }
        try {
            certifyCurrentNamespace(RdbDialect.oracle(), new ScopedDataSource(
                    url, schema, schemaPassword, null));
        } finally {
            try (Connection connection = DriverManager.getConnection(url, administrator, administratorPassword)) {
                execute(connection, "drop user " + schema + " cascade");
            }
        }
    }

    @Test
    void sqlServerEntityAnnotationsRoundTripExactly() throws Exception {
        certify(Database.SQL_SERVER, RdbDialect.sqlServer());
    }

    private static void certify(Database database, RdbDialect dialect) throws Exception {
        Properties configuration = configuration();
        String prefix = database.key + ".";
        certify(database, dialect,
                required(configuration, prefix + "url"),
                required(configuration, prefix + "user"),
                required(configuration, prefix + "password"));
    }

    private static void certify(
            Database database,
            RdbDialect dialect,
            String url,
            String user,
            String password) throws Exception {
        String namespace = "flying_orm_32_rt_" + UUID.randomUUID().toString().replace("-", "");
        boolean created = false;
        try (Connection administration = DriverManager.getConnection(url, user, password)) {
            execute(administration, database.createNamespace(namespace));
            created = true;
            DataSource scoped = new ScopedDataSource(url, user, password, database.enterNamespace(namespace));
            certifyCurrentNamespace(dialect, scoped);
        } finally {
            if (created) {
                try (Connection administration = DriverManager.getConnection(url, user, password)) {
                    execute(administration, database.dropNamespace(namespace));
                }
            }
        }
    }

    private static void certifyCurrentNamespace(RdbDialect dialect, DataSource scoped) throws Exception {
        JdbcSqlExecutor executor = JdbcSqlExecutor.create(scoped, dialect);
        JdbcFormMetadataReader reader = JdbcFormMetadataReaders.create(executor, dialect);
        JdbcSchemaClient schemaClient = JdbcSchemaClient.create(executor, dialect);
        DatabaseDescriptor descriptor = descriptor(scoped, dialect);
        try (EntityModelRegistry models = EntityModelRegistry.create(CacheRegionPolicy.disabled())) {
            EntitySchemaSynchronizer synchronizer = new EntitySchemaSynchronizer(
                    models, null, null, schemaClient, reader);

            synchronizeAndValidate(
                    synchronizer, schemaClient, reader, descriptor, dialect,
                    List.of(RoundTripOrder.class, RoundTripCustomer.class, RoundTripEvolutionV1.class));
            synchronizeAndValidate(
                    synchronizer, schemaClient, reader, descriptor, dialect,
                    List.of(RoundTripEvolutionV2.class));

            List<RelationalTableDefinition> desired = List.of(
                    entityTable(RoundTripCustomer.class),
                    entityTable(RoundTripOrder.class),
                    entityTable(RoundTripEvolutionV2.class));
            assertTrue(reader.snapshotCoverage().isComplete());
            for (RelationalTableDefinition table : desired) {
                SchemaSnapshot actual = reader.readSnapshot(table.identity().table());
                assertTrue(actual.completeTable().isPresent(), table.identity().table());
                ReviewedSchemaPlan exact = schemaClient.reviewRelational(
                        descriptor, table, reader, SchemaCompatibilityMode.EXACT);
                assertTrue(exact.steps().isEmpty(), table.identity().table());
            }
        }
    }

    private static RelationalTableDefinition entityTable(Class<?> entityType) {
        return EntitySchemaDescriptor.builder(entityType).build().table();
    }

    private static DatabaseDescriptor descriptor(DataSource dataSource, RdbDialect dialect) throws SQLException {
        try (Connection connection = dataSource.getConnection()) {
            DatabaseMetaData metadata = connection.getMetaData();
            return DatabaseDescriptor.of(
                    metadata.getDatabaseProductName(), metadata.getDatabaseProductVersion(), dialect);
        }
    }

    private static void synchronizeAndValidate(
            EntitySchemaSynchronizer synchronizer,
            JdbcSchemaClient schemaClient,
            JdbcFormMetadataReader reader,
            DatabaseDescriptor database,
            RdbDialect dialect,
            List<Class<?>> entityTypes) {
        Map<String, SchemaMigrationApproval> approvals = new LinkedHashMap<>();
        List<String> reviewedSql = new ArrayList<>();
        for (Class<?> entityType : entityTypes) {
            RelationalTableDefinition desired = entityTable(entityType);
            ReviewedSchemaPlan plan = schemaClient.reviewRelational(
                    database, desired, reader, SchemaCompatibilityMode.EXACT);
            for (var step : plan.steps()) {
                if (!step.executable()) {
                    try {
                        RelationalSchemaSqlRenderer.create(dialect.schema()).render(step.operation());
                    } catch (UnsupportedOperationException unsupported) {
                        throw new AssertionError("manual schema step " + step.operation().kind() + "/"
                                + step.operation().objectName() + ": " + unsupported.getMessage(), unsupported);
                    }
                }
            }
            assertTrue(!plan.requiresManualAction(), () -> "manual schema steps: "
                    + plan.steps().stream()
                            .filter(step -> !step.executable())
                            .map(step -> step.operation().kind() + "/" + step.operation().objectName())
                            .toList());
            plan.steps().forEach(step -> step.request().ifPresent(
                    request -> reviewedSql.add(desired.identity().table() + ": " + request.sql())));
            approvals.put(desired.identity().table(),
                          SchemaMigrationApproval.approve(plan, "local real-database certification"));
        }
        EntityRelationalSchemaSyncReport updated = synchronizer.synchronizeRelational(
                database, EntitySchemaSyncMode.FULL_UPDATE, approvals, entityTypes);
        if (!updated.successful()) {
            for (Class<?> entityType : entityTypes) {
                reader.readSnapshot(entityTable(entityType).identity().table());
            }
        }
        assertTrue(updated.successful(), () -> executionEvidence(updated) + "; reviewedSql=" + reviewedSql);
        EntityRelationalSchemaSyncReport validated = synchronizer.synchronizeRelational(
                database, EntitySchemaSyncMode.VALIDATE, entityTypes);
        assertTrue(validated.successful(), () -> executionEvidence(validated));
    }

    private static String executionEvidence(EntityRelationalSchemaSyncReport report) {
        StringBuilder evidence = new StringBuilder("mode=").append(report.mode());
        for (int resultIndex = 0; resultIndex < report.results().size(); resultIndex++) {
            var result = report.results().get(resultIndex);
            evidence.append("; result[").append(resultIndex).append("]=").append(result.status());
            for (var step : result.steps()) {
                evidence.append(" step[").append(step.order()).append("]=").append(step.status());
                step.failureSummary().ifPresent(summary -> evidence.append('(').append(summary).append(')'));
            }
            result.verification().ifPresent(verification -> evidence.append(" verification=")
                    .append(verification.status()).append(':')
                    .append(verification.operations().stream()
                            .map(operation -> operation.kind() + "/" + operation.objectName())
                            .toList()));
        }
        return evidence.toString();
    }

    private static Properties configuration() throws IOException {
        Path path = Path.of(System.getProperty("flying.orm.it.config")).toAbsolutePath().normalize();
        Properties properties = new Properties();
        try (var input = Files.newInputStream(path)) {
            properties.load(input);
        }
        return properties;
    }

    private static String required(Properties properties, String key) {
        String value = properties.getProperty(key);
        if (value == null || value.isBlank()) {
            throw new IllegalStateException("missing real-database test property: " + key);
        }
        return value.trim();
    }

    private static void execute(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }

    private enum Database {
        POSTGRESQL("postgresql") {
            @Override
            String createNamespace(String name) {
                return "create schema \"" + name + "\"";
            }

            @Override
            String enterNamespace(String name) {
                return "set search_path to \"" + name + "\"";
            }

            @Override
            String dropNamespace(String name) {
                return "drop schema \"" + name + "\" cascade";
            }
        },
        MYSQL("mysql") {
            @Override
            String createNamespace(String name) {
                return "create database `" + name
                        + "` character set utf8mb4 collate utf8mb4_0900_ai_ci";
            }

            @Override
            String enterNamespace(String name) {
                return "use `" + name + "`";
            }

            @Override
            String dropNamespace(String name) {
                return "drop database `" + name + "`";
            }
        },
        H2("h2") {
            @Override
            String createNamespace(String name) {
                return "create schema " + name;
            }

            @Override
            String enterNamespace(String name) {
                return "set schema " + name;
            }

            @Override
            String dropNamespace(String name) {
                return "drop schema " + name + " cascade";
            }
        },
        SQL_SERVER("sqlserver") {
            @Override
            String createNamespace(String name) {
                return "create database [" + name + "]";
            }

            @Override
            String enterNamespace(String name) {
                return "use [" + name + "]";
            }

            @Override
            String dropNamespace(String name) {
                return "drop database [" + name + "]";
            }
        };

        private final String key;

        Database(String key) {
            this.key = key;
        }

        abstract String createNamespace(String name);

        abstract String enterNamespace(String name);

        abstract String dropNamespace(String name);
    }

    private static final class ScopedDataSource implements DataSource {

        private final String url;
        private final String user;
        private final String password;
        private final String setupSql;

        private ScopedDataSource(String url, String user, String password, String setupSql) {
            this.url = url;
            this.user = user;
            this.password = password;
            this.setupSql = setupSql;
        }

        @Override
        public Connection getConnection() throws SQLException {
            return initialize(DriverManager.getConnection(url, user, password));
        }

        @Override
        public Connection getConnection(String username, String suppliedPassword) throws SQLException {
            return initialize(DriverManager.getConnection(url, username, suppliedPassword));
        }

        private Connection initialize(Connection connection) throws SQLException {
            try {
                if (setupSql != null && !setupSql.isBlank()) {
                    execute(connection, setupSql);
                }
                return connection;
            } catch (SQLException error) {
                connection.close();
                throw error;
            }
        }

        @Override
        public PrintWriter getLogWriter() throws SQLException {
            return DriverManager.getLogWriter();
        }

        @Override
        public void setLogWriter(PrintWriter out) throws SQLException {
            DriverManager.setLogWriter(out);
        }

        @Override
        public void setLoginTimeout(int seconds) throws SQLException {
            DriverManager.setLoginTimeout(seconds);
        }

        @Override
        public int getLoginTimeout() throws SQLException {
            return DriverManager.getLoginTimeout();
        }

        @Override
        public Logger getParentLogger() throws SQLFeatureNotSupportedException {
            return Logger.getLogger("com.flying.orm.rdb.metadata.roundtrip");
        }

        @Override
        public <T> T unwrap(Class<T> iface) throws SQLException {
            if (iface.isInstance(this)) {
                return iface.cast(this);
            }
            throw new SQLException("data source wrapper does not expose the requested type");
        }

        @Override
        public boolean isWrapperFor(Class<?> iface) {
            return iface.isInstance(this);
        }
    }

    @TableName("fo32_rt_customers")
    @TableComment("往返认证客户表")
    @TablePrimaryKey(name = "pk_fo32_rt_customers", properties = "id")
    @TableUnique(id = "customer-code", name = "uk_fo32_rt_customers_code", properties = "code")
    @TableIndex(id = "customer-created", name = "ix_fo32_rt_customers_created",
            columns = @TableIndexColumn(property = "createdAt", direction = TableIndexColumn.Direction.DESC))
    private static final class RoundTripCustomer {

        @TableId(type = IdType.AUTO)
        @TableColumn(databaseTypeId = "BIGINT", nullable = TableColumn.Nullability.NOT_NULL)
        private Long id;

        @TableColumn(databaseTypeId = "VARCHAR", length = 64,
                nullable = TableColumn.Nullability.NOT_NULL, comment = "客户编码")
        private String code;

        @TableColumn(databaseTypeId = "TIMESTAMP", temporalPrecision = 6,
                nullable = TableColumn.Nullability.NOT_NULL, defaultId = "CURRENT_TIMESTAMP")
        private LocalDateTime createdAt;
    }

    @TableName("fo32_rt_orders")
    @TableComment("往返认证订单表")
    @TablePrimaryKey(name = "pk_fo32_rt_orders", properties = "id")
    @TableForeignKey(id = "order-customer", name = "fk_fo32_rt_orders_customer",
            localProperties = "customerId", targetEntity = RoundTripCustomer.class,
            targetProperties = "id", onDelete = ReferentialAction.CASCADE)
    @TableCheck(id = "order-amount", name = "ck_fo32_rt_orders_amount", property = "amount",
            operator = TableCheck.Operator.GREATER_THAN_OR_EQUAL, literalValues = "0")
    private static final class RoundTripOrder {

        @TableId(type = IdType.AUTO)
        @TableColumn(databaseTypeId = "BIGINT", nullable = TableColumn.Nullability.NOT_NULL)
        private Long id;

        @TableColumn(databaseTypeId = "BIGINT", nullable = TableColumn.Nullability.NOT_NULL)
        private Long customerId;

        @TableColumn(databaseTypeId = "DECIMAL", precision = 12, scale = 2,
                nullable = TableColumn.Nullability.NOT_NULL, comment = "订单金额")
        private BigDecimal amount;
    }

    @TableName("fo32_rt_evolution")
    @TableComment("往返认证演进表")
    @TablePrimaryKey(name = "pk_fo32_rt_evolution", properties = "id")
    private static final class RoundTripEvolutionV1 {

        @TableId(type = IdType.AUTO)
        @TableColumn(databaseTypeId = "BIGINT", nullable = TableColumn.Nullability.NOT_NULL)
        private Long id;

        @TableColumn(databaseTypeId = "VARCHAR", length = 64)
        private String name;
    }

    @TableName("fo32_rt_evolution")
    @TableComment("往返认证演进表")
    @TablePrimaryKey(name = "pk_fo32_rt_evolution", properties = "id")
    @TableIndex(id = "evolution-status", name = "ix_fo32_rt_evolution_status",
            columns = @TableIndexColumn(property = "status"))
    private static final class RoundTripEvolutionV2 {

        @TableId(type = IdType.AUTO)
        @TableColumn(databaseTypeId = "BIGINT", nullable = TableColumn.Nullability.NOT_NULL)
        private Long id;

        @TableColumn(databaseTypeId = "VARCHAR", length = 64)
        private String name;

        @TableColumn(databaseTypeId = "VARCHAR", length = 24, comment = "演进状态")
        private String status;
    }
}
