package com.flying.orm.rdb.schema;

import com.flying.orm.core.metadata.ValueGeneration;
import com.flying.orm.core.type.DatabaseType;

import java.util.Objects;
import java.util.Optional;

/** 把统一生成策略渲染成各数据库真正支持的 identity/sequence 语法。 */
final class SchemaDialectGenerationSupport {

    private final SchemaDialectTypeSupport types;
    private final SchemaDialect.GeneratedValueStyle style;

    SchemaDialectGenerationSupport(SchemaDialectTypeSupport types, SchemaDialect.GeneratedValueStyle style) {
        this.types = Objects.requireNonNull(types, "type support must not be null");
        this.style = Objects.requireNonNull(style, "generated value style must not be null");
    }

    String generatedValueClause(ValueGeneration generation, String databaseType) {
        ValueGeneration safe = Objects.requireNonNull(generation, "value generation must not be null");
        if (!safe.generated()) {
            return "";
        }
        requireGeneratedType(databaseType);
        return switch (style) {
            case H2 -> h2(safe);
            case MYSQL -> mysql(safe);
            case POSTGRESQL -> postgresql(safe);
            case ORACLE -> oracle(safe);
            case SQL_SERVER -> sqlServer(safe);
            case NONE -> throw new IllegalArgumentException("current schema dialect does not support generated values");
        };
    }

    Optional<String> createSequenceSql(ValueGeneration generation, String databaseType) {
        ValueGeneration safe = Objects.requireNonNull(generation, "value generation must not be null");
        if (safe.strategy() != ValueGeneration.Strategy.SEQUENCE) {
            return Optional.empty();
        }
        requireGeneratedType(databaseType);
        if (style == SchemaDialect.GeneratedValueStyle.ORACLE) {
            requireOracleCache(safe.cacheSize());
        }
        String options = " start with " + safe.startWith()
                + " increment by " + safe.incrementBy() + cache(safe.cacheSize());
        return switch (style) {
            case H2, POSTGRESQL, ORACLE -> Optional.of(
                    "create sequence " + types.identifier(safe.sequenceName()) + options);
            case SQL_SERVER -> Optional.of("create sequence " + types.identifier(safe.sequenceName())
                                                   + " as " + SchemaDialectTypeSupport.requireDataType(
                                                           databaseType, "sequence data type")
                                                   + options);
            case MYSQL -> throw new IllegalArgumentException("mysql does not support named sequences");
            case NONE -> throw new IllegalArgumentException("current schema dialect does not support sequences");
        };
    }

    /** MySQL 的起始值属于 CREATE TABLE 表选项，其他方言的生成选项都在列定义或序列中。 */
    String generatedTableClause(ValueGeneration generation) {
        ValueGeneration safe = Objects.requireNonNull(generation, "value generation must not be null");
        if (style != SchemaDialect.GeneratedValueStyle.MYSQL
                || safe.strategy() != ValueGeneration.Strategy.IDENTITY
                || safe.startWith() == 1) {
            return "";
        }
        if (safe.startWith() < 1) {
            throw new IllegalArgumentException("mysql identity start must be positive");
        }
        return " auto_increment = " + safe.startWith();
    }

    Optional<String> dropSequenceSql(ValueGeneration generation) {
        ValueGeneration safe = Objects.requireNonNull(generation, "value generation must not be null");
        if (safe.strategy() != ValueGeneration.Strategy.SEQUENCE) {
            return Optional.empty();
        }
        return switch (style) {
            case H2, POSTGRESQL, ORACLE, SQL_SERVER -> Optional.of(
                    "drop sequence " + types.identifier(safe.sequenceName()));
            case MYSQL -> throw new IllegalArgumentException("mysql does not support named sequences");
            case NONE -> throw new IllegalArgumentException("current schema dialect does not support sequences");
        };
    }

    private String h2(ValueGeneration generation) {
        return switch (generation.strategy()) {
            case IDENTITY -> " generated by default as identity (start with " + generation.startWith()
                    + " increment by " + generation.incrementBy() + ")";
            case SEQUENCE -> " default next value for " + types.identifier(generation.sequenceName());
            case NONE -> "";
        };
    }

    private static String mysql(ValueGeneration generation) {
        return switch (generation.strategy()) {
            case IDENTITY -> {
                if (generation.incrementBy() != 1) {
                    throw new IllegalArgumentException("mysql identity increment must be one");
                }
                yield " auto_increment";
            }
            case SEQUENCE -> throw new IllegalArgumentException("mysql does not support named sequences");
            case NONE -> "";
        };
    }

    private String postgresql(ValueGeneration generation) {
        return switch (generation.strategy()) {
            case IDENTITY -> " generated by default as identity (start with " + generation.startWith()
                    + " increment by " + generation.incrementBy() + cache(generation.cacheSize()) + ")";
            case SEQUENCE -> " default nextval('" + sequenceLiteral(generation.sequenceName()) + "'::regclass)";
            case NONE -> "";
        };
    }

    private String sequenceLiteral(String sequenceName) {
        return types.identifier(sequenceName).replace("'", "''");
    }

    private String oracle(ValueGeneration generation) {
        requireOracleCache(generation.cacheSize());
        return switch (generation.strategy()) {
            case IDENTITY -> " generated by default on null as identity (start with " + generation.startWith()
                    + " increment by " + generation.incrementBy() + cache(generation.cacheSize()) + ")";
            case SEQUENCE -> " default " + types.identifier(generation.sequenceName()) + ".nextval";
            case NONE -> "";
        };
    }

    private String sqlServer(ValueGeneration generation) {
        return switch (generation.strategy()) {
            case IDENTITY -> " identity(" + generation.startWith() + "," + generation.incrementBy() + ")";
            case SEQUENCE -> " default next value for " + types.identifier(generation.sequenceName());
            case NONE -> "";
        };
    }

    private static String cache(int cacheSize) {
        return cacheSize == 0 ? "" : " cache " + cacheSize;
    }

    private void requireGeneratedType(String databaseType) {
        DatabaseType type = DatabaseType.of(databaseType).requireSafe("generated column data type");
        String base = type.baseName();
        boolean supported = switch (style) {
            case POSTGRESQL, H2 -> switch (base) {
                case "SMALLINT", "INTEGER", "BIGINT", "INT2", "INT4", "INT8" -> true;
                default -> false;
            };
            case MYSQL -> switch (base) {
                case "TINYINT", "SMALLINT", "MEDIUMINT", "INT", "INTEGER", "BIGINT" -> true;
                default -> false;
            };
            case ORACLE -> switch (base) {
                case "NUMBER", "NUMERIC", "DECIMAL", "INTEGER", "SMALLINT", "BIGINT" -> true;
                default -> false;
            };
            case SQL_SERVER -> switch (base) {
                case "TINYINT", "SMALLINT", "INT", "INTEGER", "BIGINT", "NUMERIC", "DECIMAL" -> true;
                default -> false;
            };
            case NONE -> false;
        };
        if (!supported) {
            throw new IllegalArgumentException("generated column requires a numeric data type: " + databaseType);
        }
        if (style == SchemaDialect.GeneratedValueStyle.SQL_SERVER
                && (base.equals("NUMERIC") || base.equals("DECIMAL"))
                && !hasZeroScale(type)) {
            throw new IllegalArgumentException(
                    "sql server generated decimal data type must have scale zero: " + type.declaration());
        }
    }

    private static boolean hasZeroScale(DatabaseType databaseType) {
        return databaseType.arguments().size() < 2 || "0".equals(databaseType.arguments().get(1));
    }

    private static void requireOracleCache(int cacheSize) {
        if (cacheSize == 1) {
            throw new IllegalArgumentException("oracle sequence cache size must be zero or at least two");
        }
    }
}
