package com.flying.orm.rdb.schema;

import com.flying.orm.core.metadata.ValueGeneration;

import java.util.Objects;
import java.util.Optional;

/** 把统一生成策略渲染成各数据库真正支持的 identity/sequence 语法。 */
final class SchemaDialectGenerationSupport {

    private final SchemaDialectTypeSupport types;
    private final SchemaDialect.GeneratedValueStyle style;

    SchemaDialectGenerationSupport(SchemaDialectTypeSupport types, SchemaDialect.GeneratedValueStyle style) {
        this.types = Objects.requireNonNull(types, "type support must not be null");
        this.style = Objects.requireNonNull(style, "generated value style must not be null");
    }

    String generatedValueClause(ValueGeneration generation, String databaseType) {
        ValueGeneration safe = Objects.requireNonNull(generation, "value generation must not be null");
        if (!safe.generated()) {
            return "";
        }
        requireNumericType(databaseType);
        return switch (style) {
            case H2 -> h2(safe);
            case MYSQL -> mysql(safe);
            case POSTGRESQL -> postgresql(safe);
            case ORACLE -> oracle(safe);
            case SQL_SERVER -> sqlServer(safe);
            case NONE -> throw new IllegalArgumentException("current schema dialect does not support generated values");
        };
    }

    Optional<String> createSequenceSql(ValueGeneration generation, String databaseType) {
        ValueGeneration safe = Objects.requireNonNull(generation, "value generation must not be null");
        if (safe.strategy() != ValueGeneration.Strategy.SEQUENCE) {
            return Optional.empty();
        }
        requireNumericType(databaseType);
        String options = " start with " + safe.startWith()
                + " increment by " + safe.incrementBy() + cache(safe.cacheSize());
        return switch (style) {
            case H2, POSTGRESQL -> Optional.of("create sequence " + types.identifier(safe.sequenceName()) + options);
            case ORACLE -> Optional.of("create sequence " + types.identifier(safe.sequenceName()) + options);
            case SQL_SERVER -> Optional.of("create sequence " + types.identifier(safe.sequenceName())
                                                   + " as " + SchemaDialectTypeSupport.requireDataType(databaseType,
                                                                                                          "sequence data type")
                                                   + options);
            case MYSQL -> throw new IllegalArgumentException("mysql does not support named sequences");
            case NONE -> throw new IllegalArgumentException("current schema dialect does not support sequences");
        };
    }

    private String h2(ValueGeneration generation) {
        return switch (generation.strategy()) {
            case IDENTITY -> " generated by default as identity (start with " + generation.startWith()
                    + " increment by " + generation.incrementBy() + ")";
            case SEQUENCE -> " default next value for " + types.identifier(generation.sequenceName());
            case NONE -> "";
        };
    }

    private static String mysql(ValueGeneration generation) {
        return switch (generation.strategy()) {
            case IDENTITY -> " auto_increment";
            case SEQUENCE -> throw new IllegalArgumentException("mysql does not support named sequences");
            case NONE -> "";
        };
    }

    private String postgresql(ValueGeneration generation) {
        return switch (generation.strategy()) {
            case IDENTITY -> " generated by default as identity (start with " + generation.startWith()
                    + " increment by " + generation.incrementBy() + cache(generation.cacheSize()) + ")";
            case SEQUENCE -> " default nextval('" + sequenceLiteral(generation.sequenceName()) + "'::regclass)";
            case NONE -> "";
        };
    }

    private String sequenceLiteral(String sequenceName) {
        return types.identifier(sequenceName).replace("'", "''");
    }

    private String oracle(ValueGeneration generation) {
        return switch (generation.strategy()) {
            case IDENTITY -> " generated by default on null as identity (start with " + generation.startWith()
                    + " increment by " + generation.incrementBy() + cache(generation.cacheSize()) + ")";
            case SEQUENCE -> " default " + types.identifier(generation.sequenceName()) + ".nextval";
            case NONE -> "";
        };
    }

    private String sqlServer(ValueGeneration generation) {
        return switch (generation.strategy()) {
            case IDENTITY -> " identity(" + generation.startWith() + "," + generation.incrementBy() + ")";
            case SEQUENCE -> " default next value for " + types.identifier(generation.sequenceName());
            case NONE -> "";
        };
    }

    private static String cache(int cacheSize) {
        return cacheSize == 0 ? "" : " cache " + cacheSize;
    }

    private static void requireNumericType(String databaseType) {
        String normalized = SchemaDialectTypeSupport.requireDataType(databaseType,
                                                                      "generated column data type")
                                                       .toLowerCase(java.util.Locale.ROOT);
        if (!(normalized.startsWith("number") || normalized.startsWith("numeric")
                || normalized.startsWith("decimal") || normalized.startsWith("bigint")
                || normalized.startsWith("integer") || normalized.startsWith("int")
                || normalized.startsWith("smallint") || normalized.startsWith("tinyint"))) {
            throw new IllegalArgumentException("generated column requires a numeric data type: " + databaseType);
        }
    }
}
